### ISSUE TITLE
NoMethodError: undefined method `each_with_index' for nil:NilClass

### ISSUE THREAD

**Issue by mgmacri** [jmettraux/rufus-scheduler#160]
{ 15648420 rufus-scheduler intercepted an error:
      15648420   job:
      15648420     Rufus::Scheduler::EveryJob "10m" {}
      15648420   error:
      15648420     15648420
      15648420     NoMethodError
      15648420     undefined method `each_with_index' for nil:NilClass
      15648420       /home/matthew/.rvm/gems/ruby-2.1.2/gems/twitter_ebooks-3.1.0/lib            /twitter_ebooks/suffix.rb:59:in `block in generate'
      15648420       /home/matthew/.rvm/gems/ruby-2.1.2/gems/twitter_ebooks-3.1.0/lib    /twitter_ebooks/suffix.rb:56:in `upto'
      15648420       /home/matthew/.rvm/gems/ruby-2.1.2/gems/twitter_ebooks-3.1.0/lib/twitter_ebooks/suffix.rb:56:in `generate'
      15648420       /home/matthew/.rvm/gems/ruby-2.1.2/gems/twitter_ebooks-3.1.0/lib/twitter_ebooks/model.rb:220:in `make_statement'
      15648420       bots.rb:35:in `block in on_startup'
      15648420       /home/matthew/.rvm/gems/ruby-2.1.2/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:234:in `call'
      15648420       /home/matthew/.rvm/gems/ruby-2.1.2/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:234:in `do_call'
      15648420       /home/matthew/.rvm/gems/ruby-2.1.2/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:258:in `do_trigger'
      15648420       /home/matthew/.rvm/gems/ruby-2.1.2/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:300:in `block (3 levels) in start_work_thread'
      15648420       /home/matthew/.rvm/gems/ruby-2.1.2/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:303:in `call'
       15648420       /home/matthew/.rvm/gems/ruby-2.1.2/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:303:in `block (2 levels) in start_work_thread'
      15648420       /home/matthew/.rvm/gems/ruby-2.1.2/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:289:in `loop'
      15648420       /home/matthew/.rvm/gems/ruby-2.1.2/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:289:in `block in start_work_thread'

bot.rb:

    scheduler.every('10m') do
           statement = model.make_statement(140)
          tweet(statement)
        end

Trying to create a markov chain twitterbot following this guide https://sts10.github.io/blog/2014/12/23/guide-create-markov-twitter-bot/ unsure where I went wrong or how to reconcile this issue. I'm alright with ruby, by no means a seasoned professional, but, I can get by just fine. Thanks for taking the time to check out my issue and I hope to hear from you soon. :+1: 

This bot is running on ruby 2.1.2p95, please let me know if that is problematic for rufus-scheduler.

**Comment by jmettraux** [comment]
Hello,

if you take the time to read the error message, you'll notice it happens at

```
  15648420     undefined method `each_with_index' for nil:NilClass
  15648420       /home/matthew/.rvm/gems/ruby-2.1.2/gems/twitter_ebooks-3.1.0/lib/twitter_ebooks/suffix.rb:59:in `block in generate'
```

Investigate from there. Rufus-scheduler is merely reporting the issue.

Best regards.

**Comment by mgmacri** [comment]
Thank you very much, just so I'm crystal clear on this: rufus-scheduler is inheriting the method 'each_with_index' from twitter_ebooks-3.1.0 which is located in /path/to/suffix.rb and ought to be defined on line 59, but, clearly is not defined.

**Comment by jmettraux** [comment]
No, rufus-scheduler is not inheriting anything from any other gem.

Twitter_ebooks-3.1.0 is calling `each_with_index` on something that is `nil` at `/home/matthew/.rvm/gems/ruby-2.1.2/gems/twitter_ebooks-3.1.0/lib/twitter_ebooks/suffix.rb:59`

And yes, clearly, `each_with_index` is not defined there, it's merely called. `each_with_index` is (unless diverted) defined at http://ruby-doc.org/core-2.2.2/Enumerable.html#method-i-each_with_index

Good luck!

**Comment by mgmacri** [comment]
Thanks for the clarification, should I resolve this issue would it be alright if I posted the results here, or should I do so on the twitter_ebooks github page?

**Comment by jmettraux** [comment]
You're welcome.

Feel free to post a link to the resolution from here.

Best regards.
