### ISSUE TITLE
"*/0" results in infinite loop with CronLine.new

### ISSUE THREAD

**Issue by simook** [jmettraux/rufus-scheduler#202]
This issue occurs when using the every syntax that has a value of `0`. While the value is invalid and should not be used in cron expression, it does result with CronLine going into an infinite loop. Expected behavior would be to raise an exception.

Found in versions 3.1.1 to 3.2.0. 

Steps to reproduce:
1. Use the every syntax `*/0` in the cron expression.
2. `irb`
3. `require "rufus-scheduler"`
2. `Rufus::Scheduler::CronLine.new("*/0 * * * *")`.

GDB Stacktrace:
```bash
from /Users/kyle.simukka/.rvm/gems/ruby-2.0.0-p576/gems/rufus-scheduler-3.2.0/lib/rufus/scheduler/cronline.rb:408:in `call'
	from /Users/kyle.simukka/.rvm/gems/ruby-2.0.0-p576/gems/rufus-scheduler-3.2.0/lib/rufus/scheduler/cronline.rb:408:in `block in parse_range'
	from /Users/kyle.simukka/.rvm/gems/ruby-2.0.0-p576/gems/rufus-scheduler-3.2.0/lib/rufus/scheduler/cronline.rb:406:in `loop'
	from /Users/kyle.simukka/.rvm/gems/ruby-2.0.0-p576/gems/rufus-scheduler-3.2.0/lib/rufus/scheduler/cronline.rb:406:in `parse_range'
	from /Users/kyle.simukka/.rvm/gems/ruby-2.0.0-p576/gems/rufus-scheduler-3.2.0/lib/rufus/scheduler/cronline.rb:364:in `block in parse_item'
	from /Users/kyle.simukka/.rvm/gems/ruby-2.0.0-p576/gems/rufus-scheduler-3.2.0/lib/rufus/scheduler/cronline.rb:364:in `map'
	from /Users/kyle.simukka/.rvm/gems/ruby-2.0.0-p576/gems/rufus-scheduler-3.2.0/lib/rufus/scheduler/cronline.rb:364:in `parse_item'
	from /Users/kyle.simukka/.rvm/gems/ruby-2.0.0-p576/gems/rufus-scheduler-3.2.0/lib/rufus/scheduler/cronline.rb:68:in `initialize'
	from (irb):2:in `new'
```

**Comment by simook** [comment]
https://github.com/jmettraux/rufus-scheduler/pull/203

**Comment by jmettraux** [comment]
Argh, already fixed on my side.

**Comment by jmettraux** [comment]
OK, discarding my commit and taking yours in.

**Comment by jmettraux** [comment]
Thanks a lot.
