### ISSUE TITLE
Cannot determine timezone from "VET"

### ISSUE THREAD

**Issue by jmettraux** [jmettraux/rufus-scheduler#233]
@sofiabravo103 wrote in gh-222 : 

> Hi, I got the cannot determine timezone from nil error and added the fixes suggested in de faqs but the error continuous in the line where I start rufus: 

> Here is my code: 
```ruby
ENV['TZ'] = 'America/Caracas' 
Rufus::Scheduler.singleton.every(
  "#{@harvest_plan.hours_between}h",
  :times => repetitions, :first_at => @harvest_plan.start_date
) do
  CreateHarvestFromPlanJob.perform_later
end
```

>And here is the error
```
ArgumentError (cannot determine timezone from "VET (etz:"America/Caracas",tnz:"VET",tzid:"constant")):
```

> I am running Rails 4.2.4, Ruby 2.2.2 and Rufus 3.3.2. (It was also me on stackoverflow about issue #231 )

> What's going on?

**Comment by jmettraux** [comment]
@sofiabravo103 Hello

What operating system are you running on?
What is the "de faq" thing you are referring to? Can you please include a link to it?

Thanks in advance

**Comment by jmettraux** [comment]
And also, may I have the complete error backtrace?

Thanks in advance!

**Comment by sofiabravo103** [comment]
Ubuntu 14.04.5 LTS. 
 I don't think it will help, but here is the complete error backtrace:
```

ArgumentError (cannot determine timezone from nil (etz:"Caracas",tnz:"Caracas",tzid:"constant")):
  app/controllers/harvest_plans_controller.rb:36:in `schedule_harvest'
  app/controllers/harvest_plans_controller.rb:17:in `create'


```

**Comment by jmettraux** [comment]
Thanks.

May I please see the code of your `harvest_plans_controller.rb` especially around line 36 ? (so says your backtrace).

**Comment by sofiabravo103** [comment]
You have it, it's this line:

`Rufus::Scheduler.singleton.every "#{@harvest_plan.hours_between}h",`

Also "de faqs" was a typo, sorry, I meant to say "the faqs", as in frequently asked questions in the README.

**Comment by jmettraux** [comment]
OK, so it's not the complete error backtrace, Rails must be filtering it for you. Else you would see the call to `Rufus::Scheduler::ZoTime#initialize` where the ArgumentError is raised.

Getting inspiration from gh-230, could you please try with:

```ruby
ENV['TZ'] = Time.zone.name
Rufus::Scheduler.singleton.every(
  "#{@harvest_plan.hours_between}h",
  :times => repetitions, :first_at => @harvest_plan.start_date
) do
  CreateHarvestFromPlanJob.perform_later
end
```

So that it will pick Rails's defined timezone (I've read in #230 that it's set in Rails `application.rb`).

**Comment by sofiabravo103** [comment]
Already did, almost same error:

`ArgumentError (cannot determine timezone from nil (etz:"Caracas",tnz:"Caracas",tzid:"constant")):`

**Comment by jmettraux** [comment]
What does

```ruby
p Time.zone.class
p Time.zone
ENV['TZ'] = Time.zone.name
Rufus::Scheduler.singleton.every(
  "#{@harvest_plan.hours_between}h",
  :times => repetitions, :first_at => @harvest_plan.start_date
) do
  CreateHarvestFromPlanJob.perform_later
end
```

yield?

I am interested in the `p`s precise output.

**Comment by sofiabravo103** [comment]
```
2.2.2 :001 > p Time.zone.class
ActiveSupport::TimeZone
 => ActiveSupport::TimeZone 

```

```
2.2.2 :002 > p Time.zone
#<ActiveSupport::TimeZone:0x0000000555b860 @name="Caracas", @utc_offset=nil, @tzinfo=#<TZInfo::TimezoneProxy: America/Caracas>, @current_period=#<TZInfo::TimezonePeriod: #<TZInfo::TimezoneTransitionDefinition: #<TZInfo::TimeOrDateTime: 1462086000>,#<TZInfo::TimezoneOffset: -14400,0,VET>>,nil>>
 => #<ActiveSupport::TimeZone:0x0000000555b860 @name="Caracas", @utc_offset=nil, @tzinfo=#<TZInfo::TimezoneProxy: America/Caracas>, @current_period=#<TZInfo::TimezonePeriod: #<TZInfo::TimezoneTransitionDefinition: #<TZInfo::TimeOrDateTime: 1462086000>,#<TZInfo::TimezoneOffset: -14400,0,VET>>,nil>> 

```

But this output might be different from what would have been when I reported the issue. I did an Ubuntu upgrade and it cleared the ArgumentError. This timezone is really peculiar, it has changed twice in recent time (last one in 2016), and not as in daylight saving or anything normal like that. It was -4:30 at the start of 2016 and now it's -4. The Venezuelan president changes the timezone for political reasons whenever he feels in the mood. I though the timezone issues could be fixed with an OS upgrade, and I think they did. I don't know if you still want to fix the ArgumentError, but if you do want to feel free to ask me anything else. Just wanted lo let you know that my code is working now.

**Comment by jmettraux** [comment]
> Just wanted lo let you know that my code is working now.

I am glad to learn that I spent two hours of my life on a problem that is not my fault.

**Comment by sofiabravo103** [comment]
Great attitude. In my opinion it is still not ok to see an ArgumentError from your code, that should not be the way to find out there is an issue with timezone. I figured it based on a guess, could have been on this problem for weeks.

**Comment by jmettraux** [comment]
> Great attitude

Please elaborate.

> In my opinion it is still not OK to see an ArgumentError from your code

What should it do then?

**Comment by jmettraux** [comment]
> But thanks for helping out anyway.

That's the "thanks" I was hoping for.

**Comment by mosca1337** [comment]
I'm hitting a similar issue on OSX. Interestingly enough, this error started showing yesterday March 13th 2016 when daylight savings time switched.

```
foreman run bundle exec sidekiq -q default
2017-03-15T06:11:36.260Z 1288 TID-oxdf05wxk INFO: Running in ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
2017-03-15T06:11:36.260Z 1288 TID-oxdf05wxk INFO: See LICENSE and the LGPL-3.0 for licensing details.
2017-03-15T06:11:36.260Z 1288 TID-oxdf05wxk INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2017-03-15T06:11:36.260Z 1288 TID-oxdf05wxk INFO: Booting Sidekiq 4.2.7 with redis options {:url=>"redis://127.0.0.1"}
2017-03-15T06:11:36.262Z 1288 TID-oxdf05wxk INFO: Loading Schedule
2017-03-15T06:11:36.262Z 1288 TID-oxdf05wxk INFO: Scheduling update_sitemap_job {"cron"=>"0 0 2 * * * America/Los_Angeles", "class"=>"UpdateSitemapJob", "queue"=>"default"}
2017-03-15T06:11:36.597Z 1288 TID-oxdf05wxk WARN: {"context":"Exception during Sidekiq lifecycle event.","event":"startup"}
2017-03-15T06:11:36.597Z 1288 TID-oxdf05wxk WARN: ArgumentError: cannot determine timezone from nil (etz:nil,tnz:"PDT",tzid:nil)
2017-03-15T06:11:36.597Z 1288 TID-oxdf05wxk WARN: /Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.3.2/lib/rufus/scheduler/zotime.rb:41:in `initialize'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.3.2/lib/rufus/scheduler/zotime.rb:198:in `new'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.3.2/lib/rufus/scheduler/zotime.rb:198:in `now'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.3.2/lib/rufus/scheduler.rb:561:in `start'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.3.2/lib/rufus/scheduler.rb:109:in `initialize'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sidekiq-scheduler-2.1.0/lib/sidekiq/scheduler.rb:365:in `new'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sidekiq-scheduler-2.1.0/lib/sidekiq/scheduler.rb:365:in `new_rufus_scheduler'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sidekiq-scheduler-2.1.0/lib/sidekiq/scheduler.rb:193:in `rufus_scheduler'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sidekiq-scheduler-2.1.0/lib/sidekiq/scheduler.rb:375:in `new_job'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sidekiq-scheduler-2.1.0/lib/sidekiq/scheduler.rb:114:in `block in load_schedule_job'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sidekiq-scheduler-2.1.0/lib/sidekiq/scheduler.rb:107:in `each'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sidekiq-scheduler-2.1.0/lib/sidekiq/scheduler.rb:107:in `load_schedule_job'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sidekiq-scheduler-2.1.0/lib/sidekiq/scheduler.rb:68:in `block in load_schedule!'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sidekiq-scheduler-2.1.0/lib/sidekiq/scheduler.rb:66:in `each'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sidekiq-scheduler-2.1.0/lib/sidekiq/scheduler.rb:66:in `load_schedule!'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sidekiq-scheduler-2.1.0/lib/sidekiq-scheduler/manager.rb:29:in `start'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sidekiq-scheduler-2.1.0/lib/sidekiq-scheduler.rb:33:in `block (2 levels) in <top (required)>'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sidekiq-4.2.7/lib/sidekiq/util.rb:54:in `call'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sidekiq-4.2.7/lib/sidekiq/util.rb:54:in `block in fire_event'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sidekiq-4.2.7/lib/sidekiq/util.rb:52:in `each'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sidekiq-4.2.7/lib/sidekiq/util.rb:52:in `fire_event'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sidekiq-4.2.7/lib/sidekiq/cli.rb:79:in `run'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sidekiq-4.2.7/bin/sidekiq:12:in `<top (required)>'
/Users/mosca1337/.rbenv/versions/2.2.3/bin/sidekiq:23:in `load'
/Users/mosca1337/.rbenv/versions/2.2.3/bin/sidekiq:23:in `<top (required)>'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `load'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:27:in `run'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/cli.rb:332:in `exec'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/cli.rb:20:in `dispatch'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/cli.rb:11:in `start'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/exe/bundle:34:in `block in <top (required)>'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/exe/bundle:26:in `<top (required)>'
/Users/mosca1337/.rbenv/versions/2.2.3/bin/bundle:23:in `load'
/Users/mosca1337/.rbenv/versions/2.2.3/bin/bundle:23:in `<main>'
```

**Comment by jmettraux** [comment]
@mosca1337 please read https://github.com/jmettraux/rufus-scheduler#i-get-zotimerb41in-initialize-cannot-determine-timezone-from-nil

Thanks!

**Comment by jmettraux** [comment]
@mosca1337 you might also be interested in testing what is currently on master, I have put on some detection code for the system's current timezone, as seen in https://github.com/jmettraux/rufus-scheduler/issues/240

Tell me if that change fixes the issue for you.

Thanks in advance.

**Comment by mosca1337** [comment]
```
TZ="America/Los_Angeles" rails console
Running via Spring preloader in process 1471
Loading development environment (Rails 4.2.6)
[1] pry(main)> Rufus::Scheduler::ZoTime.now
=> #<Rufus::Scheduler::ZoTime:0x007ff4301c3c58 @seconds=1489558877.130253, @time=nil, @zone=#<TZInfo::DataTimezone: America/Los_Angeles>>
```

```
rails console
Running via Spring preloader in process 1486
Loading development environment (Rails 4.2.6)
[1] pry(main)> Rufus::Scheduler::ZoTime.now
ArgumentError: cannot determine timezone from nil (etz:nil,tnz:"PDT",tzid:nil)
from /Users/mosca1337/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.3.2/lib/rufus/scheduler/zotime.rb:41:in `initialize'
```

Resolved temporarily with:
```
TZ="America/Los_Angeles" foreman run worker
2017-03-15T06:22:41.089Z 1504 TID-ovsbjpts0 INFO: Running in ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
2017-03-15T06:22:41.089Z 1504 TID-ovsbjpts0 INFO: See LICENSE and the LGPL-3.0 for licensing details.
2017-03-15T06:22:41.089Z 1504 TID-ovsbjpts0 INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2017-03-15T06:22:41.089Z 1504 TID-ovsbjpts0 INFO: Booting Sidekiq 4.2.7 with redis options {:url=>"redis://127.0.0.1"}
2017-03-15T06:22:41.092Z 1504 TID-ovsbjpts0 INFO: Loading Schedule
```

The daylight savings time change may have been a very odd coincidence?

**Comment by mosca1337** [comment]
Upgrading from 3.3.2 to 3.3.4 solved this (should have checked for updates first). Thanks for the quick help!

```
Installing rufus-scheduler 3.3.4 (was 3.3.2)
```

```
foreman run worker
2017-03-15T06:25:20.877Z 1548 TID-ovnexw9ok INFO: Running in ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
2017-03-15T06:25:20.877Z 1548 TID-ovnexw9ok INFO: See LICENSE and the LGPL-3.0 for licensing details.
2017-03-15T06:25:20.877Z 1548 TID-ovnexw9ok INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2017-03-15T06:25:20.877Z 1548 TID-ovnexw9ok INFO: Booting Sidekiq 4.2.7 with redis options {:url=>"redis://127.0.0.1"}
2017-03-15T06:25:20.880Z 1548 TID-ovnexw9ok INFO: Loading Schedule
```

**Comment by jmettraux** [comment]
OK, you're welcome.
