### ISSUE TITLE
3.3.x timezone change broke Windows compatibility 

### ISSUE THREAD

**Issue by animeavi** [jmettraux/rufus-scheduler#237]
I can't run this simple code anymore without downgrading to 3.2.2. I'm using Ruby 2.2.4 from RubyInstaller dot org.

```
#!/usr/bin/env ruby

require 'rubygems'
require 'rufus/scheduler'

scheduler = Rufus::Scheduler.new
scheduler.every '5m' do
  puts "5 minutes have passed."
end

scheduler.join

```

The exception I get 
```
C:/Ruby22/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.3.3/lib/rufus/scheduler/zotime.rb:41:in `initialize': cannot determine timezone from nil (etz:nil,tnz:"Eastern Standard Time",tzid:nil) (ArgumentError)
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.3.3/lib/rufus/scheduler/zotime.rb:203:in `new'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.3.3/lib/rufus/scheduler/zotime.rb:203:in `now'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.3.3/lib/rufus/scheduler.rb:561:in `start'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.3.3/lib/rufus/scheduler.rb:109:in `initialize'
        from c.rb:6:in `new'
        from c.rb:6:in `<main>'
```

**Comment by jmettraux** [comment]
Hello,

does that fix it?

```ruby
#!/usr/bin/env ruby

require 'rubygems'
require 'rufus/scheduler'

ENV['TZ'] = 'America/New_York'

scheduler = Rufus::Scheduler.new
scheduler.every '5m' do
  puts "5 minutes have passed."
end

scheduler.join
```

**Comment by animeavi** [comment]
I still get the exception.
```
C:/Ruby22/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.3.3/lib/rufus/scheduler/zotime.rb:41:in `initialize': cannot determine timezone from nil (etz:"America/New_York",tnz:"Ame",tzid:nil) (ArgumentError)
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.3.3/lib/rufus/scheduler/zotime.rb:203:in `new'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.3.3/lib/rufus/scheduler/zotime.rb:203:in `now'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.3.3/lib/rufus/scheduler.rb:561:in `start'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.3.3/lib/rufus/scheduler.rb:109:in `initialize'
        from c.rb:8:in `new'
        from c.rb:8:in `<main>'
```

**Comment by jmettraux** [comment]
OK, I'll try to find a Windows system and fix that somehow.

Best regards.

**Comment by animeavi** [comment]
Thank you. I'll Use 3.2.2 for now.

**Comment by jmettraux** [comment]
@animeavi 

another question: what happens when you install the 'tzinfo-data' gem and run that updated script:

```ruby
#!/usr/bin/env ruby

require 'rubygems'
require 'tzinfo/data'
require 'rufus/scheduler'

ENV['TZ'] = 'America/New_York'

scheduler = Rufus::Scheduler.new
scheduler.every '5m' do
  puts "5 minutes have passed."
end

scheduler.join
```

Thanks in advance.

**Comment by jmettraux** [comment]
OK, forget it. I could find a windows system, it's still working and it hasn't killed me yet. I see the same problem even with tzinfo-data loaded.

I will try to fix that.

**Comment by jmettraux** [comment]
> I see the same problem even with tzinfo-data loaded.

No, I was wrong, having tzinfo-data and doing `ENV['TZ'] = 'America/New_York' solves the issue.

I will update the FAQ.

**Comment by jmettraux** [comment]
https://github.com/jmettraux/rufus-scheduler#i-get-zotimerb41in-initialize-cannot-determine-timezone-from-nil

**Comment by jmettraux** [comment]
Solved by enhancing documentation and error message.
