### ISSUE TITLE
quickstart.rb error (nomethoderror)

### ISSUE THREAD

**Issue by erlangp** [jmettraux/rufus-scheduler#244]
Hello.. i get error when execute quickstart.rb
How to fix this error? Thank you.

file: **quickstart.rb**

```
require 'rufus-scheduler'

scheduler = Rufus::Scheduler.new

#scheduler.in '10d' do
#  # do something in 10 days
#end

#scheduler.at '2030/12/12 23:30:00' do
#  # do something at a given point in time
#end

#scheduler.every '3h' do
#  # do something every 3 hours
#end

#scheduler.cron '5 0 * * *' do
#  # do something every day, five minutes after midnight
#  # (see "man 5 crontab" in your terminal)
#end

scheduler.every '10s' do
  # do something every 10 seconds
  puts 'test'
end

```

Result:

```
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/et-orbi-1.0.2/lib/et-orbi.rb:368:in `render_nozone_time': undefined method `period_for_local' for nil:NilClass (NoMethodError)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/et-orbi-1.0.2/lib/et-orbi.rb:197:in `initialize'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/et-orbi-1.0.2/lib/et-orbi.rb:17:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/et-orbi-1.0.2/lib/et-orbi.rb:17:in `now'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/et-orbi-1.0.2/lib/et-orbi.rb:156:in `now'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.4.0/lib/rufus/scheduler.rb:543:in `start'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.4.0/lib/rufus/scheduler.rb:89:in `initialize'
        from quickstart.rb:3:in `new'
        from quickstart.rb:3:in `<main>'

```

**Comment by jmettraux** [comment]
Hello,

thanks for reporting this issue.

I've fixed the `undefined method` problem in the source gem: https://github.com/floraison/et-orbi/commit/c0bccc02849d4ab61e3d13b78bd06e52d1ab4eea

Could you please upgrade your `et-orbi` gem to 1.0.3 (`bundle update et-orbi`) and try again?

Another error message should appear with suggestions on what to do.

**Comment by erlangp** [comment]
i get this message after update:

```

C:\Users\SONY\Desktop>ruby quickstart.rb
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/et-orbi-1.0.3/lib/et-orbi.rb:195:in `initialize': cannot determine timezone from nil (ArgumentError)
(secs:1491540926.3591192,utc~:"0047-04-07 04:55:26.359119176864624",ltz~:nil)
(etz:nil,tnz:"Malay Peninsula Standard Time",tzid:"constant",rv:"2.3.3",rp:"x64-mingw32",eov:"1.0.3",rorv:nil,astz:nil,
debian:nil,centos:nil,osx:nil)
Try setting `ENV['TZ'] = 'Continent/City'` in your script (see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/et-orbi-1.0.3/lib/et-orbi.rb:17:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/et-orbi-1.0.3/lib/et-orbi.rb:17:in `now'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/et-orbi-1.0.3/lib/et-orbi.rb:156:in `now'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.4.0/lib/rufus/scheduler.rb:543:in `start'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.4.0/lib/rufus/scheduler.rb:89:in `initialize'
        from quickstart.rb:3:in `new'
        from quickstart.rb:3:in `<main>'

```

**Comment by jmettraux** [comment]
Then, please try with the following `quickstart.rb`:
```ruby
ENV['TZ'] = 'Asia/Kuala_Lumpur'

require 'rufus-scheduler'

scheduler = Rufus::Scheduler.new

scheduler.every '10s' do
  # do something every 10 seconds
  puts 'test'
end

scheduler.join
```
and tell me how it goes.

**Comment by erlangp** [comment]
error message gone :D thanks!

**Comment by jmettraux** [comment]
You're welcome!
