### ISSUE TITLE
cron schedule causes endless memory allocation injection

### ISSUE THREAD

**Issue by piavka** [jmettraux/rufus-scheduler#255]
the following bad schedule `*/0 * * * *` causes `Rufus::Scheduler.parse_cron(...)` to block and consume all server memory until
```
/opt/ruby/embedded/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.1.7/lib/rufus/scheduler/cronline.rb:406:in `block in parse_range': failed to allocate memory (NoMemoryError)
    from /opt/ruby/embedded/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.1.7/lib/rufus/scheduler/cronline.rb:403:in `loop'
    from /opt/ruby/embedded/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.1.7/lib/rufus/scheduler/cronline.rb:403:in `parse_range'
    from /opt/ruby/embedded/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.1.7/lib/rufus/scheduler/cronline.rb:361:in `block in parse_item'
    from /opt/ruby/embedded/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.1.7/lib/rufus/scheduler/cronline.rb:361:in `map'
    from /opt/ruby/embedded/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.1.7/lib/rufus/scheduler/cronline.rb:361:in `parse_item'
    from /opt/ruby/embedded/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.1.7/lib/rufus/scheduler/cronline.rb:68:in `initialize'
    from /opt/ruby/embedded/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.1.7/lib/rufus/scheduler/util.rb:61:in `new'
    from /opt/ruby/embedded/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.1.7/lib/rufus/scheduler/util.rb:61:in `parse_cron'
```

**Comment by jmettraux** [comment]
Fixed in https://github.com/jmettraux/rufus-scheduler/issues/202

Thanks anyway.
