### ISSUE TITLE
How to fix 'rufus-scheduler intercepted an error'

### ISSUE THREAD

**Issue by surajshah1** [jmettraux/rufus-scheduler#294]
`{ 47017144876640 rufus-scheduler intercepted an error:
  47017144876640   job:
  47017144876640     Rufus::Scheduler::EveryJob "3600s" {:first_in=>0}
  47017144876640   error:
  47017144876640     47017144876640
  47017144876640     Errno::ECONNREFUSED
  47017144876640     Failed to open TCP connection to :80 (Connection refused - connect(2) for nil port 80)
  47017144876640       /usr/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect'
  47017144876640       /usr/lib/ruby/2.5.0/net/http.rb:936:in `block in connect'
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on 0.0.0.0:3035, CTRL+C to stop
  47017144876640       /usr/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
  47017144876640       /usr/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
  47017144876640       /usr/lib/ruby/2.5.0/net/http.rb:935:in `connect'
  47017144876640       /usr/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
  47017144876640       /usr/lib/ruby/2.5.0/net/http.rb:909:in `start'
  47017144876640       /usr/lib/ruby/2.5.0/net/http.rb:609:in `start'
  47017144876640       /home/suraj/percipient_dash/jobs/sonar.rb:58:in `block in <top (required)>'
  47017144876640       /var/lib/gems/2.5.0/gems/rufus-scheduler-3.4.2/lib/rufus/scheduler/jobs.rb:210:in `do_call'
  47017144876640       /var/lib/gems/2.5.0/gems/rufus-scheduler-3.4.2/lib/rufus/scheduler/jobs.rb:254:in `trigger_now'
  47017144876640       /var/lib/gems/2.5.0/gems/rufus-scheduler-3.4.2/lib/rufus/scheduler/jobs.rb:296:in `block (3 levels) in start_work_thread'
  47017144876640       /var/lib/gems/2.5.0/gems/rufus-scheduler-3.4.2/lib/rufus/scheduler/jobs.rb:299:in `block (2 levels) in start_work_thread'
  47017144876640       /var/lib/gems/2.5.0/gems/rufus-scheduler-3.4.2/lib/rufus/scheduler/jobs.rb:285:in `loop'
  47017144876640       /var/lib/gems/2.5.0/gems/rufus-scheduler-3.4.2/lib/rufus/scheduler/jobs.rb:285:in `block in start_work_thread'
  47017144876640   tz:
  47017144876640     ENV['TZ']: 
  47017144876640     Time.now: 2019-07-22 11:31:11 -0700
  47017144876640     local_tzone: #<TZInfo::DataTimezone: America/Los_Angeles>
  47017144876640   et-orbi:
  47017144876640     (etz:nil,tnz:"PDT",tziv:"1.2.5",tzidv:nil,rv:"2.5.5",rp:"x86_64-linux-gnu",win:false,rorv:nil,astz:nil,eov:"1.2.1",eotnz:#<TZInfo::DataTimezone: America/Los_Angeles>,eotnfz:"-0700",eotlzn:"America/Los_Angeles",eotnfZ:"PDT",debian:"America/Los_Angeles",centos:nil,osx:"America/Los_Angeles")
  47017144876640   scheduler:
  47017144876640     object_id: 47017139337900
  47017144876640     opts:
  47017144876640       {}
  47017144876640       frequency: 0.3
  47017144876640       scheduler_lock: #<Rufus::Scheduler::NullLock:0x000055860fc6f260>
  47017144876640       trigger_lock: #<Rufus::Scheduler::NullLock:0x000055860fc6f238>
  47017144876640     uptime: 0.3569216728210449 (356)
  47017144876640     down?: false
  47017144876640     threads: 2
  47017144876640       thread: #<Thread:0x000055860fc887b0@/var/lib/gems/2.5.0/gems/rufus-scheduler-3.4.2/lib/rufus/scheduler.rb:546 sleep>
  47017144876640       thread_key: rufus_scheduler_47017139337900
  47017144876640       work_threads: 1
  47017144876640         active: 1
  47017144876640         vacant: 0
  47017144876640         max_work_threads: 28
  47017144876640       mutexes: {}
  47017144876640     jobs: 5
  47017144876640       at_jobs: 0
  47017144876640       in_jobs: 0
  47017144876640       every_jobs: 5
  47017144876640       interval_jobs: 0
  47017144876640       cron_jobs: 0
  47017144876640     running_jobs: 1
  47017144876640     work_queue: 0
} 47017144876640 .
Exception: wrong number of arguments (given 1, expected 0)
`

**Comment by surajshah1** [comment]
fixed
