### ISSUE TITLE
Error starting Docker image named "engineerbetter/worker-image"

### ISSUE THREAD

**Issue by ranadeep-sh** [jmettraux/rufus-scheduler#298]
Kindly help out with the possible root cause of the following error.

The rufus scheduler is part of a Docker image that I am trying to run. The said Docker image was pulled locally from https://hub.docker.com/r/engineerbetter/worker-image

```
$ docker image pull engineerbetter/worker-image
--
$ winpty docker run -it --rm engineerbetter/worker-image bash                                                                                                                                    recording status                                                                                                                                                                                 { 11997600 rufus-scheduler intercepted an error:                                                                                                                                                   11997600   job:                                                                                                                                                                                  11997600     Rufus::Scheduler::EveryJob "10s" {}                                                                                                                                                 11997600   error:                                                                                                                                                                                11997600     11997600                                                                                                                                                                            11997600     StorageError                                                                                                                                                                        11997600     No URL set                                                                                                                                                                          11997600       /worker/lib/people_data_service.rb:25:in `rescue in people'                                                                                                                       11997600       /worker/lib/people_data_service.rb:20:in `people'                                                                                                                                 11997600       /worker/lib/status_manager.rb:19:in `record_random_status'                                                                                                                        11997600       /worker/lib/app_scheduler.rb:15:in `block in run'                                                                                                                                 11997600       /usr/local/bundle/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler/jobs.rb:234:in `do_call'                                                                                         11997600       /usr/local/bundle/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler/jobs.rb:278:in `trigger_now'                                                                                     11997600       /usr/local/bundle/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler/jobs.rb:320:in `block (3 levels) in start_work_thread'                                                           11997600       /usr/local/bundle/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler/jobs.rb:323:in `block (2 levels) in start_work_thread'                                                           11997600       /usr/local/bundle/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler/jobs.rb:309:in `loop'                                                                                            11997600       /usr/local/bundle/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler/jobs.rb:309:in `block in start_work_thread'                                                                      11997600   tz:                                                                                                                                                                                   11997600     ENV['TZ']:                                                                                                                                                                          11997600     Time.now: 2019-10-20 20:41:43 +0000                                                                                                                                                 11997600     local_tzone: #                                                                                                                                           11997600   scheduler:                                                                                                                                                                            11997600     object_id: 17793920                                                                                                                                                                 11997600     opts:                                                                                                                                                                               11997600       {}                                                                                                                                                                                11997600       frequency: 0.3                                                                                                                                                                    11997600       scheduler_lock: #                                                                                                                    11997600       trigger_lock: #                                                                                                                      11997600     uptime: 10.227404832839966 (10s227)                                                                                                                                                 11997600     down?: false                                                                                                                                                                        11997600     threads: 2                                                                                                                                                                          11997600       thread: #                                                                                                                                                11997600       thread_key: rufus_scheduler_17793920                                                                                                                                              11997600       work_threads: 1                                                                                                                                                                   11997600         active: 1                                                                                                                                                                       11997600         vacant: 0                                                                                                                                                                       11997600         max_work_threads: 28                                                                                                                                                            11997600       mutexes: {}                                                                                                                                                                       11997600     jobs: 1                                                                                                                                                                             11997600       at_jobs: 0                                                                                                                                                                        11997600       in_jobs: 0                                                                                                                                                                        11997600       every_jobs: 1
--
```

**Comment by jmettraux** [comment]
```
{ 11997600 rufus-scheduler intercepted an error:   
  11997600     Rufus::Scheduler::EveryJob "10s" {}
  11997600   error:
  11997600     StorageError
  11997600     No URL set
  11997600       /worker/lib/people_data_service.rb:25:in `rescue in people'
  11997600       /worker/lib/people_data_service.rb:20:in `people'
  11997600       /worker/lib/status_manager.rb:19:in `record_random_status' 
  11997600       /worker/lib/app_scheduler.rb:15:in `block in run'
```

**Comment by jmettraux** [comment]
Hello,

this is not a rufus-scheduler issue. Rufus-scheduler is simply reporting an error in your application. `StorageError "No URL set"`.

I guess (I can only guess) that you've misconfigured your app and forget to set some URL config for your storage. Set that and rufus-scheduler will stop passing the error to you.

Closing the issue as it does not belong here. Rufus-scheduler is merely the messenger.

Best regards.
